id = "autocorrect"
name = "AutoCorrect"
description = "AutoCorrect is a linter and formatter to help you to spellcheck typos, correct spaces, words, and punctuations between CJK."
version = "0.2.0"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/huacnlee/zed-autocorrect"

[language_servers.autocorrect]
name = "AutoCorrect LSP Server"
languages = [
    "HTML",
    "JSON",
    "ERB",
    "Markdown",
    "JavaScript",
    "TypeScript",
    "CSS",
    "JSX",
    "TSX",
    "Vue.js",
    "YAML",
    "TOML",
    "XML",
    "Rust",
    "Ruby",
    "Python",
    "Go",
    "SQL",
    "Plain Text",
    "Unknown",
]
code_action_kinds = ["quickfix"]
